#   _____ ______ __  __    _____
#  / ____|  ____|  \/  |  / ____|
# | (___ | |__  | \  / | | |     ___  _ __ ___
#  \___ \|  __| | |\/| | | |    / _ \| '__/ _ \
#  ____) | |____| |  | | | |___| (_) | | |  __/
# |_____/|______|_|  |_|  \_____\___/|_|  \___|
#
#
# +-------------------------+
# | Database Configuration  |
# +-------------------------+
database:
  host: 'mysql://localhost:3306'
  username: 'root'
  password: 'toor'
  schema: 'sem_core'


# +-------------------------+
# |

