name: SEM-Core
main: net.corecrafted.semcore.AppLaunch
version: 1.2.04-BETA
descripton: Core Implementation of Survival Expert Mode Server
author: ThisTNTSquid
depend: [PlaceholderAPI, LuckPerms]
commands:
  sem:
    description: SEM Core main command
    usage: /sem [argument]